apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "todo.fullname" . }}
  labels:
    app: {{ template "todo.name" . }}
    chart: {{ template "todo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
   rules:
    - host: {{ .Values.web.host }}
      http:
         paths:
          - path: /
            backend:
               serviceName: {{ template "todo.fullname" . }}
               servicePort: 80
   tls:
    - hosts:
      - {{ .Values.web.host }}
