# Default values for kafka-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

kafka_connect_ui:
  connect_url: cp-kafka-cp-kafka-connect:8083

image:
  repository: landoop/kafka-connect-ui
  tag: latest
  pullPolicy: IfNotPresent

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
