apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "kafka-schema-registry-ui.fullname" . }}
  labels:
    app: {{ include "kafka-schema-registry-ui.name" . }}
    chart: {{ include "kafka-schema-registry-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kafka-schema-registry-ui.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "kafka-schema-registry-ui.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SCHEMAREGISTRY_URL
              value: "http://{{ .Values.kafka_schema_registry_ui.schema_registry_url }}"
            - name: PROXY
              value: "true"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
