kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: aws-service-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-service-operator
subjects:
- kind: ServiceAccount
  name: aws-service-operator
  namespace: {{ .Release.Namespace }}
